apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitserver
  namespace: fleet-upsert
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-fleet-upsert-gitserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-fleet-upsert-gitserver
    spec:
      affinity: {}
      containers:
      - image: shpwrck/gitserver:20.04
        imagePullPolicy: Always
        name: gitserver
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/git/example
          name: git-repo
        - mountPath: /etc/nginx/sites-enabled/
          name: git-conf
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - git
        - --bare
        - init
        - /var/git/example
        image: alpine/git
        imagePullPolicy: Always
        name: init-git
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/git/example
          name: git-repo
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: git-repo
      - configMap:
          defaultMode: 256
          name: git-conf
          optional: false
        name: git-conf
      - configMap:
          defaultMode: 256
          name: nginx-conf
          optional: false
        name: nginx-conf
