apiVersion: v1
kind: Service
metadata:
  name: gitserver
  namespace: fleet-upsert
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-fleet-upsert-gitserver
  sessionAffinity: None
  type: ClusterIP

